// Code generated by MockGen. DO NOT EDIT.
// Source: gophermart/cmd/gophermart/utils (interfaces: AccrualService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	resty "github.com/go-resty/resty/v2"
	gomock "github.com/golang/mock/gomock"
)

// MockAccrualService is a mock of AccrualService interface.
type MockAccrualService struct {
	ctrl     *gomock.Controller
	recorder *MockAccrualServiceMockRecorder
}

// MockAccrualServiceMockRecorder is the mock recorder for MockAccrualService.
type MockAccrualServiceMockRecorder struct {
	mock *MockAccrualService
}

// NewMockAccrualService creates a new mock instance.
func NewMockAccrualService(ctrl *gomock.Controller) *MockAccrualService {
	mock := &MockAccrualService{ctrl: ctrl}
	mock.recorder = &MockAccrualServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccrualService) EXPECT() *MockAccrualServiceMockRecorder {
	return m.recorder
}

// MakePurchase mocks base method.
func (m *MockAccrualService) MakePurchase(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MakePurchase", arg0)
}

// MakePurchase indicates an expected call of MakePurchase.
func (mr *MockAccrualServiceMockRecorder) MakePurchase(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakePurchase", reflect.TypeOf((*MockAccrualService)(nil).MakePurchase), arg0)
}

// RegisterRewards mocks base method.
func (m *MockAccrualService) RegisterRewards() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterRewards")
}

// RegisterRewards indicates an expected call of RegisterRewards.
func (mr *MockAccrualServiceMockRecorder) RegisterRewards() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRewards", reflect.TypeOf((*MockAccrualService)(nil).RegisterRewards))
}

// RequestToAccrualByOrderumber mocks base method.
func (m *MockAccrualService) RequestToAccrualByOrderumber(arg0 int) (*resty.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestToAccrualByOrderumber", arg0)
	ret0, _ := ret[0].(*resty.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestToAccrualByOrderumber indicates an expected call of RequestToAccrualByOrderumber.
func (mr *MockAccrualServiceMockRecorder) RequestToAccrualByOrderumber(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestToAccrualByOrderumber", reflect.TypeOf((*MockAccrualService)(nil).RequestToAccrualByOrderumber), arg0)
}
