// Code generated by MockGen. DO NOT EDIT.
// Source: gophermart/cmd/gophermart/clients (interfaces: AccrualClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	resty "github.com/go-resty/resty/v2"
	gomock "github.com/golang/mock/gomock"
)

// MockAccrualClient is a mock of AccrualClient interface.
type MockAccrualClient struct {
	ctrl     *gomock.Controller
	recorder *MockAccrualClientMockRecorder
}

// MockAccrualClientMockRecorder is the mock recorder for MockAccrualClient.
type MockAccrualClientMockRecorder struct {
	mock *MockAccrualClient
}

// NewMockAccrualClient creates a new mock instance.
func NewMockAccrualClient(ctrl *gomock.Controller) *MockAccrualClient {
	mock := &MockAccrualClient{ctrl: ctrl}
	mock.recorder = &MockAccrualClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccrualClient) EXPECT() *MockAccrualClientMockRecorder {
	return m.recorder
}

// MakePurchase mocks base method.
func (m *MockAccrualClient) MakePurchase(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MakePurchase", arg0)
}

// MakePurchase indicates an expected call of MakePurchase.
func (mr *MockAccrualClientMockRecorder) MakePurchase(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakePurchase", reflect.TypeOf((*MockAccrualClient)(nil).MakePurchase), arg0)
}

// RegisterRewards mocks base method.
func (m *MockAccrualClient) RegisterRewards() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterRewards")
}

// RegisterRewards indicates an expected call of RegisterRewards.
func (mr *MockAccrualClientMockRecorder) RegisterRewards() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRewards", reflect.TypeOf((*MockAccrualClient)(nil).RegisterRewards))
}

// RequestToAccrualByOrderumber mocks base method.
func (m *MockAccrualClient) RequestToAccrualByOrderumber(arg0 int) (*resty.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestToAccrualByOrderumber", arg0)
	ret0, _ := ret[0].(*resty.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestToAccrualByOrderumber indicates an expected call of RequestToAccrualByOrderumber.
func (mr *MockAccrualClientMockRecorder) RequestToAccrualByOrderumber(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestToAccrualByOrderumber", reflect.TypeOf((*MockAccrualClient)(nil).RequestToAccrualByOrderumber), arg0)
}
