// Code generated by MockGen. DO NOT EDIT.
// Source: gophermart/cmd/gophermart/user (interfaces: UserService)

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// GetUserIDFromCookie mocks base method.
func (m *MockUserService) GetUserIDFromCookie(arg0 *http.Request) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDFromCookie", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDFromCookie indicates an expected call of GetUserIDFromCookie.
func (mr *MockUserServiceMockRecorder) GetUserIDFromCookie(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDFromCookie", reflect.TypeOf((*MockUserService)(nil).GetUserIDFromCookie), arg0)
}

// SetUserIDCookie mocks base method.
func (m *MockUserService) SetUserIDCookie(arg0 http.ResponseWriter, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserIDCookie", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserIDCookie indicates an expected call of SetUserIDCookie.
func (mr *MockUserServiceMockRecorder) SetUserIDCookie(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserIDCookie", reflect.TypeOf((*MockUserService)(nil).SetUserIDCookie), arg0, arg1)
}
