version: '3'

includes:
  taskfile_lint: ./Taskfile_lint.yml

vars:
  binary_name: gophermart
  docker_image: debian:bookworm-slim
  app_path: cmd/gophermart

tasks:
  all:
    deps: [clean, run]

  build:
    cmds:
      - echo "Building {{.binary_name}}..."
      - go build -o {{.binary_name}} ./{{.app_path}}
    deps: [lint]

  run:
    cmds:
      - echo "Running {{.binary_name}}..."
      - ./{{.binary_name}}
    deps: [build]

  clean:
    cmds:
      - echo "Cleaning up..."
      - rm -f {{.binary_name}}
  
  lint:
    cmds:
      - echo "Linting {{.binary_name}}..."
      - "task taskfile_lint:lint"

  docker-run:
    cmds:
      - echo "Running {{.binary_name}} in Docker..."
      - sudo docker run --rm -v $(pwd):/app -w /app {{.docker_image}} ./{{.binary_name}}
    deps: [build]


