name: Go Application

on:
  push:
    branches:
      - working_branch

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v2
      with:
        go-version: '1.x'

    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}
# run: 
# sudo apt-get install -y task
# sudo sh -c "curl -s https://taskfile.dev/install.sh | sh"

    - name: Build and run using Taskfile
      run: task docker-run